### ISSUE TITLE
V2: {Airport} is not a base of {Airline} bad request after resetting and changing base

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#329]
![image](https://user-images.githubusercontent.com/38160197/101936476-e673e480-3be0-11eb-936c-d357d9303203.png)

**Current behavior:** Nothing pops on on the screen, in the console there is a bad request error
**Expected behavior:** Route setup menu
**How to reproduce:** On a new airline build the headquarter, then rebuild/declare bankruptcy. After that build again the headquarter in a different airport from the previous one, when you try to setup a flight to any airport that error happens.

You get stuck and you can't do anything, the only option is to rebuild/declare bankruptcy again and set the headquarter in the original airport.

**Comment by patsonluk** [comment]
did u see the HQ icon changes to the new base at least?

**Comment by Edoebzd** [comment]
Yes, the icon changes as usual
![image](https://user-images.githubusercontent.com/38160197/101938538-cb56a400-3be3-11eb-881b-dce487948edd.png)

**Comment by patsonluk** [comment]
### Cause
Steps below:
1. If selected a link before, then declaring bankruptcy would NOT set js `selectedLink` to `undefined`
2. When a base is built, it runs `buildBase` in `airline.js`
```
updateAllPanels(activeAirline.id)
	    	showWorldMap()
	    	if (scale == 1 && isHeadquarter) {
	    		$('#planLinkFromAirportId').val(activeAirline.headquarterAirport.airportId)
	    		loadAllCountries() //has a home country now, reload country info
	    	}
```
3. `showWorldMap` triggers error, as `selectedLink` is non null, but such a link is not found on the map UI anymore
4. the exception prevents the statement `$('#planLinkFromAirportId').val(activeAirline.headquarterAirport.airportId)` from running
5. when starting a new link, it checks `planLinkFromAirportId` which is stuck to the old HQ value

## Solution
Pretty ugly coding here. 

1. The plan link logic should not really rely on a global field `planLinkFromAirportId`, it's messy to rely on different parts of the code logic to clean up that value properly
2. `selectedLink` as global var is also prone to problem

It would require quite a bit of rewrites to solve the 2 root cause tho. For now we will

1. Ensure `selectedLink` is set to undefined on airline resets
2. Set the `$('#planLinkFromAirportId').val(activeAirline.headquarterAirport.airportId)` first thing after setting up HQ
