### ISSUE TITLE
Negative value in fare

### ISSUE THREAD

**Issue by Gojapa** [patsonluk/airline#56]
It's possible to pay passagers to fly in your airline

**Comment by patsonluk** [comment]
Fixed !

In fact someone did set it to a very negative value and screwed up my simulation :|

The path finding algorithm bounces back and forth from the negative route cities (since it decreases the cost)

And the route traversal algorithm has both `predecessorMap[airport A]` and `precedessorMap[airport B]` with the same link which causes traversal failure as far as those 2 cities are involved as the part of the route (screwed up the whole brazil in this case)

**Comment by Gojapa** [comment]
Oh it was me !sorry, I was suspecting a bit from that forum post,gonna be more careful and avoid breaking the game next time

**Comment by patsonluk** [comment]
lol no worries! i am surprised that the algorithm cannot handle negative values well
